"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { isAdministrator, loadPoolRoom, supabase } from "@/lib/supabase";

type Player = { id: string; name: string; nickname?: string; color: string; active?: boolean };
type Game = { id: string; number: number; player1: string; player2: string; winner: string; type: string; notes?: string; startTime?: string; series?: string };
type Session = { id: string; date: string; name?: string; notes?: string; playerIds: string[]; games: Game[]; createdAt: string };
type Data = { version: 1; players: Player[]; sessions: Session[] };
type View = "dashboard" | "players" | "history" | "standings" | "head" | "data" | "session";

const STORAGE = "steves-pool-room-v1";
const COLORS = ["#22c55e", "#38bdf8", "#f59e0b", "#a78bfa", "#fb7185", "#2dd4bf", "#f97316", "#60a5fa", "#e879f9", "#a3e635"];
const TYPES = ["8-Ball", "9-Ball", "10-Ball", "Straight Pool", "Cutthroat", "Other"];
const empty: Data = { version: 1, players: [], sessions: [] };
const today = () => new Date().toISOString().slice(0, 10);
const initials = (p?: Player) => p ? p.name.split(/\s+/).map(x => x[0]).join("").slice(0, 2).toUpperCase() : "?";
const display = (p?: Player) => p ? (p.nickname || p.name) : "Unknown";
const pct = (wins: number, total: number) => total ? `${(wins / total * 100).toFixed(1)}%` : "—";

function stats(data: Data) {
  return data.players.map(player => {
    const games = data.sessions.flatMap(s => s.games.map(g => ({ ...g, date: s.date, session: s.name }))).filter(g => g.player1 === player.id || g.player2 === player.id).sort((a,b) => a.date.localeCompare(b.date) || a.number-b.number);
    const wins = games.filter(g => g.winner === player.id).length;
    let current = 0, best = 0, run = 0;
    for (const g of games) { run = g.winner === player.id ? run + 1 : 0; best = Math.max(best, run); }
    for (let i=games.length-1; i>=0 && games[i].winner===player.id; i--) current++;
    const types: Record<string, number> = {}; games.filter(g=>g.winner===player.id).forEach(g=>types[g.type]=(types[g.type]||0)+1);
    const opponents = data.players.filter(p=>p.id!==player.id).map(op=>{ const h=games.filter(g=>g.player1===op.id||g.player2===op.id); return { opponent: op, games:h.length, wins:h.filter(g=>g.winner===player.id).length }; }).filter(x=>x.games);
    return { player, days: data.sessions.filter(s=>s.playerIds.includes(player.id)).length, games: games.length, wins, losses: games.length-wins, percentage: games.length ? wins/games.length : 0, current, best, recent: games.length ? (games.at(-1)!.winner===player.id ? "W" : "L") : "—", types, opponents };
  }).sort((a,b)=>b.percentage-a.percentage || b.wins-a.wins || a.player.name.localeCompare(b.player.name));
}

function Avatar({ player, small=false }: { player?: Player; small?: boolean }) { return <span className={`avatar ${small ? "small" : ""}`} style={{ background: player?.color }}>{initials(player)}</span>; }
function Modal({ title, children, close }: { title: string; children: React.ReactNode; close:()=>void }) { return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-title"><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="Close">×</button></div>{children}</div></div>; }

export default function Home() {
  const [data,setData]=useState<Data>(empty), [ready,setReady]=useState(false), [view,setView]=useState<View>("dashboard"), [active,setActive]=useState<string>();
  const [playerModal,setPlayerModal]=useState<Player|"new">(), [sessionModal,setSessionModal]=useState<Session|"new">(), [gameModal,setGameModal]=useState<Game|"new">(), [toast,setToast]=useState("");
  const [h2h,setH2h]=useState<[string,string]>(["",""]); const importRef=useRef<HTMLInputElement>(null);
  const [user,setUser]=useState<User|null>(null),[admin,setAdmin]=useState(false),[loadError,setLoadError]=useState(""),[offline,setOffline]=useState(false),[updatedAt,setUpdatedAt]=useState<Date>(),[authOpen,setAuthOpen]=useState(false),[migrationReport,setMigrationReport]=useState("");
  const refresh=async()=>{try{setLoadError("");const cloud=await loadPoolRoom();setData({version:1,players:cloud.players.map(p=>({id:p.id,name:p.name,nickname:p.nickname||undefined,color:p.color,active:p.is_active})),sessions:cloud.days.map(s=>({id:s.id,date:s.date,name:s.name||undefined,notes:s.notes||undefined,playerIds:(s.play_day_players??[]).map(p=>p.player_id),games:(s.games??[]).filter(g=>!g.deleted_at).map(g=>({id:g.id,number:g.game_number,player1:g.player_1_id,player2:g.player_2_id,winner:g.winner_id,type:g.game_type,notes:g.notes||undefined,startTime:g.start_time||undefined,series:g.series||undefined})),createdAt:s.created_at}))});const timestamps=[...cloud.players.map(p=>p.updated_at||p.created_at),...cloud.days.flatMap(d=>[d.updated_at||d.created_at,...(d.games??[]).map(g=>g.updated_at||g.created_at)])].filter((value):value is string=>Boolean(value));setUpdatedAt(timestamps.length?new Date(Math.max(...timestamps.map(value=>new Date(value).getTime()))):new Date());setOffline(false)}catch(error){setLoadError(error instanceof Error?error.message:"Unable to load the pool room");setOffline(!navigator.onLine)}finally{setReady(true)}};
  useEffect(()=>{void refresh();void supabase.auth.getUser().then(({data:{user}})=>setUser(user));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setUser(session?.user??null));const channel=supabase.channel("pool-room-live").on("postgres_changes",{event:"*",schema:"public"},()=>void refresh()).subscribe();const online=()=>{setOffline(false);void refresh()},offlineNow=()=>setOffline(true);window.addEventListener("online",online);window.addEventListener("offline",offlineNow);return()=>{subscription.unsubscribe();void supabase.removeChannel(channel);window.removeEventListener("online",online);window.removeEventListener("offline",offlineNow)}},[]);
  useEffect(()=>{if(!user){setAdmin(false);return}void isAdministrator(user.id).then(setAdmin).catch(()=>setAdmin(false))},[user]);
  const standings=useMemo(()=>stats(data),[data]); const session=data.sessions.find(s=>s.id===active);
  const sorted=[...data.sessions].sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));
  const activePlayers=data.players.filter(p=>p.active!==false);
  const notify=(s:string)=>{setToast(s); setTimeout(()=>setToast(""),2400)};
  const openSession=(id:string)=>{setActive(id);setView("session")};
  const savePlayer=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!admin)return;const f=new FormData(e.currentTarget),name=String(f.get("name")||"").trim();if(!name)return;if(playerModal==="new"&&activePlayers.length>=10){notify("Player limit reached (10)");return}const record={name,nickname:String(f.get("nickname")||"").trim()||null,color:String(f.get("color")),is_active:true};const result=playerModal==="new"?await supabase.from("players").insert(record):await supabase.from("players").update(record).eq("id",playerModal!.id);if(result.error){notify(result.error.message);return}setPlayerModal(undefined);await refresh();notify("Player saved")};
  const saveSession=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!admin)return;const f=new FormData(e.currentTarget),ids=f.getAll("players").map(String);if(!ids.length){notify("Select at least one player");return}const record={date:String(f.get("date")),name:String(f.get("name")||"").trim()||null,notes:String(f.get("notes")||"").trim()||null};let id=sessionModal==="new"?"":sessionModal!.id;if(sessionModal==="new"){const {data:created,error}=await supabase.from("play_days").insert(record).select("id").single();if(error){notify(error.message);return}id=created.id}else{const {error}=await supabase.from("play_days").update(record).eq("id",id);if(error){notify(error.message);return}await supabase.from("play_day_players").delete().eq("play_day_id",id)}const {error}=await supabase.from("play_day_players").insert(ids.map(player_id=>({play_day_id:id,player_id})));if(error){notify(error.message);return}setSessionModal(undefined);await refresh();openSession(id);notify("Play day saved")};
  const saveGame=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!session||!admin)return;const f=new FormData(e.currentTarget),p1=String(f.get("p1")),p2=String(f.get("p2")),winner=String(f.get("winner"));if(p1===p2||![p1,p2].includes(winner)){notify("Choose two players and their winner");return}const number=gameModal==="new"?Math.max(0,...session.games.map(x=>x.number))+1:Number(f.get("number")),record={play_day_id:session.id,game_number:number,player_1_id:p1,player_2_id:p2,winner_id:winner,game_type:String(f.get("type")),notes:String(f.get("notes")||"")||null,start_time:String(f.get("time")||"")||null,series:String(f.get("series")||"")||null,deleted_at:null};const result=gameModal==="new"?await supabase.from("games").insert(record):await supabase.from("games").update(record).eq("id",gameModal!.id);if(result.error){notify(result.error.message);return}localStorage.setItem("pool-last-type",record.game_type);setGameModal(undefined);await refresh();notify(`Game ${number} saved`)};
  const removePlayer=async(p:Player)=>{if(!admin||!confirm(`Archive ${p.name}? Historical games will remain.`))return;const {error}=await supabase.from("players").update({is_active:false}).eq("id",p.id);if(error)notify(error.message);else{await refresh();notify("Player archived")}};
  const removeSession=async(s:Session)=>{if(!admin||!confirm(`Archive ${s.name||s.date} and hide its games? History will remain in the database.`))return;const {error}=await supabase.from("play_days").update({deleted_at:new Date().toISOString()}).eq("id",s.id);if(error)notify(error.message);else{await refresh();setView("history");notify("Play day archived")}};
  const exportJSON=()=>download(`steves-pool-room-${today()}.json`,JSON.stringify(data,null,2),"application/json");
  const exportCSV=()=>{const q=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const rows=[["Date","Session","Game","Player 1","Player 2","Winner","Type","Start Time","Series","Notes"],...sorted.flatMap(s=>s.games.map(g=>[s.date,s.name,g.number,display(data.players.find(p=>p.id===g.player1)),display(data.players.find(p=>p.id===g.player2)),display(data.players.find(p=>p.id===g.winner)),g.type,g.startTime,g.series,g.notes]))];download(`steves-pool-room-${today()}.csv`,rows.map(r=>r.map(q).join(",")).join("\n"),"text/csv")};
  const importData=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const x=JSON.parse(String(reader.result));if(x.version!==1||!Array.isArray(x.players)||!Array.isArray(x.sessions)||x.players.length>10)throw Error();if(!admin)throw Error();if(confirm(`Import ${x.players.length} players and ${x.sessions.length} play days to Supabase? Existing cloud records are not removed.`)){localStorage.setItem(STORAGE,JSON.stringify(x));localStorage.removeItem("steves-pool-room-cloud-migrated");void migrateLocal();notify("Cloud import started");}}catch{notify("That file is not a valid Pool Room export");}};reader.readAsText(file);e.target.value="";};
  const migrateLocal=async()=>{if(!admin)return;setMigrationReport("Importing…");try{if(localStorage.getItem("steves-pool-room-cloud-migrated"))throw new Error("This browser backup was already imported.");const raw=localStorage.getItem(STORAGE);if(!raw)throw new Error("No local browser backup was found.");const old=JSON.parse(raw) as Data;if(!Array.isArray(old.players)||!Array.isArray(old.sessions))throw new Error("The browser backup is invalid.");const playerMap=new Map<string,string>();for(const p of old.players){const {data:created,error}=await supabase.from("players").insert({name:p.name,nickname:p.nickname||null,color:p.color,is_active:true}).select("id").single();if(error)throw error;playerMap.set(p.id,created.id)}for(const s of old.sessions){const {data:day,error}=await supabase.from("play_days").insert({date:s.date,name:s.name||null,notes:s.notes||null}).select("id").single();if(error)throw error;const participantRows=s.playerIds.map(id=>playerMap.get(id)).filter((id):id is string=>Boolean(id)).map(player_id=>({play_day_id:day.id,player_id}));if(participantRows.length){const result=await supabase.from("play_day_players").insert(participantRows);if(result.error)throw result.error}const gameRows=s.games.map(g=>({play_day_id:day.id,game_number:g.number,player_1_id:playerMap.get(g.player1),player_2_id:playerMap.get(g.player2),winner_id:playerMap.get(g.winner),game_type:g.type,notes:g.notes||null,start_time:g.startTime||null,series:g.series||null}));if(gameRows.length){const result=await supabase.from("games").insert(gameRows);if(result.error)throw result.error}}localStorage.setItem("steves-pool-room-cloud-migrated",new Date().toISOString());setMigrationReport(`Success: imported ${old.players.length} players, ${old.sessions.length} play days, and ${old.sessions.reduce((n,s)=>n+s.games.length,0)} games. The local backup was kept.`);await refresh()}catch(error){setMigrationReport(`Import failed: ${error instanceof Error?error.message:"Unknown error"}`)}};
  if(!ready)return <div className="state-screen"><span className="spinner"/><h1>Opening Steve&apos;s Pool Room…</h1><p>Loading the latest results from the cloud.</p></div>;
  return <div className="app-shell">
    <aside><div className="brand"><span className="brand-mark">8</span><div><b>Steve&apos;s</b><small>POOL ROOM</small></div></div><nav>{([ ["dashboard","▦","Dashboard"],["players","♟","Players"],["history","◷","Play Days"],["standings","♛","Standings"],["head","↔","Head-to-Head"],["data","⇩","Data"]] as [View,string,string][]).map(([v,i,l])=><button key={v} className={view===v||v==="history"&&view==="session"?"active":""} onClick={()=>setView(v)}><span>{i}</span>{l}</button>)}</nav><div className="aside-stat"><small>THE ROOM</small><b>{activePlayers.length}<span>/10 active</span></b><b>{data.sessions.reduce((n,s)=>n+s.games.length,0)}<span>games logged</span></b><button className="auth-button" onClick={()=>user?void supabase.auth.signOut():setAuthOpen(true)}>{user?(admin?"Admin · Sign out":"Sign out"):"Admin sign in"}</button></div></aside>
    <main><header><button className="mobile-logo" onClick={()=>setView("dashboard")}>⑧</button><div><p className="eyebrow">STEVE&apos;S POOL ROOM</p><h1>{view==="session"?(session?.name||"Play Day"):({dashboard:"Dashboard",players:"Players",history:"Play Days",standings:"Overall Standings",head:"Head-to-Head",data:"Data Management"} as Record<string,string>)[view]}</h1><small className="updated">{offline?"Offline — showing last loaded results":loadError?"Cloud unavailable":updatedAt?`Updated ${updatedAt.toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}`:"Connecting…"}</small></div>{admin&&<button className="primary header-action" disabled={!activePlayers.length} onClick={()=>setSessionModal("new")}>＋ New Play Day</button>} {!user&&<button className="secondary header-login" onClick={()=>setAuthOpen(true)}>Admin</button>}</header>{loadError&&<div className="error-banner"><b>Couldn&apos;t refresh cloud data.</b> {loadError} <button onClick={()=>void refresh()}>Try again</button></div>}
      {view==="dashboard"&&<Dashboard admin={admin} data={data} standings={standings} sessions={sorted} open={openSession} add={()=>setSessionModal("new")}/>}
      {view==="players"&&<section><div className="section-heading"><div><h2>Player roster</h2><p>Up to 10 active players. Archived players remain in historical results.</p></div>{admin&&<button className="primary" disabled={activePlayers.length>=10} onClick={()=>setPlayerModal("new")}>＋ Add Player</button>}</div>{!activePlayers.length?<Empty icon="♟" title="No active players yet" text={admin?"Add the people who play in your pool room.":"An administrator has not added the roster yet."}/>:<div className="player-grid">{activePlayers.map(p=><article className="player-card" key={p.id}><Avatar player={p}/><div><h3>{p.name}</h3><p>{p.nickname?`“${p.nickname}”`:"No nickname"}</p></div>{admin&&<><button className="icon-button" onClick={()=>setPlayerModal(p)}>✎</button><button className="icon-button danger" onClick={()=>void removePlayer(p)}>×</button></>}</article>)}</div>}</section>}
      {view==="history"&&<section><div className="section-heading"><div><h2>Every day at the table</h2><p>Newest sessions appear first.</p></div>{admin&&<button className="primary" disabled={!activePlayers.length} onClick={()=>setSessionModal("new")}>＋ New Play Day</button>}</div>{!sorted.length?<Empty icon="◷" title="No play days yet" text={admin?"Start a play day, pick the players, and rack 'em up.":"Results will appear here after the first play day."}/>:<div className="session-list">{sorted.map(s=><button key={s.id} onClick={()=>openSession(s.id)}><div className="date-tile"><b>{new Date(s.date+"T12:00:00").toLocaleDateString(undefined,{day:"2-digit"})}</b><span>{new Date(s.date+"T12:00:00").toLocaleDateString(undefined,{month:"short"})}</span></div><div className="grow"><h3>{s.name||"Pool Night"}</h3><p>{s.playerIds.map(id=>display(data.players.find(p=>p.id===id))).join(" · ")}</p></div><b>{s.games.length}<small> games</small></b><span>›</span></button>)}</div>}</section>}
      {view==="standings"&&<Standings rows={standings}/>}
      {view==="head"&&<HeadToHead data={data} ids={h2h} setIds={setH2h}/>}
      {view==="data"&&<section><div className="section-heading"><div><h2>Cloud backups</h2><p>Export the permanent Supabase records at any time.</p></div></div><div className="data-grid"><article className="panel"><span className="big-icon">⇩</span><h3>Export a backup</h3><p>JSON preserves relationships and CSV opens in a spreadsheet.</p><div className="button-row"><button className="primary" onClick={exportJSON}>Export JSON</button><button className="secondary" onClick={exportCSV}>Export CSV</button></div></article>{admin&&<><article className="panel"><span className="big-icon">⇧</span><h3>Import JSON</h3><p>Choose a previously exported file to validate it before cloud recovery.</p><button className="secondary" onClick={()=>importRef.current?.click()}>Choose file</button><input hidden ref={importRef} type="file" accept="application/json,.json" onChange={importData}/></article><article className="panel migration"><span className="big-icon">☁</span><h3>One-time browser migration</h3><MigrationPreview/><p>Duplicates are blocked after a successful import. Your local copy is never erased.</p><button className="primary" onClick={()=>void migrateLocal()}>Import local data to cloud</button>{migrationReport&&<div className="migration-report" role="status">{migrationReport}</div>}</article></>}</div></section>}
      {view==="session"&&session&&<SessionView admin={admin} session={session} data={data} edit={()=>setSessionModal(session)} add={()=>setGameModal("new")} editGame={setGameModal} removeGame={async g=>{if(!confirm(`Delete game ${g.number}? The historical record will be preserved.`))return;const {error}=await supabase.from("games").update({deleted_at:new Date().toISOString()}).eq("id",g.id);if(error)notify(error.message);else{await refresh();notify("Game removed")}}} remove={()=>void removeSession(session)}/>}
    </main>
    <div className="mobile-nav">{([ ["dashboard","▦","Home"],["players","♟","Players"],["history","◷","Days"],["standings","♛","Stats"],["head","↔","H2H"]] as [View,string,string][]).map(([v,i,l])=><button key={v} className={view===v||v==="history"&&view==="session"?"active":""} onClick={()=>setView(v)}><span>{i}</span>{l}</button>)}</div>
    {admin&&playerModal&&<PlayerForm player={playerModal} index={activePlayers.length} close={()=>setPlayerModal(undefined)} save={savePlayer}/>} {admin&&sessionModal&&<SessionForm session={sessionModal} players={activePlayers} close={()=>setSessionModal(undefined)} save={saveSession}/>} {admin&&gameModal&&session&&<GameForm game={gameModal} session={session} players={data.players} close={()=>setGameModal(undefined)} save={saveGame}/>} {authOpen&&<AuthModal close={()=>setAuthOpen(false)} notify={notify}/>} {toast&&<div className="toast">✓ {toast}</div>}
  </div>;
}

function Dashboard({admin,data,standings,sessions,open,add}:{admin:boolean;data:Data;standings:ReturnType<typeof stats>;sessions:Session[];open:(id:string)=>void;add:()=>void}){const games=data.sessions.reduce((n,s)=>n+s.games.length,0),leader=standings.find(s=>s.games),active=[...standings].sort((a,b)=>b.games-a.games)[0],streak=[...standings].sort((a,b)=>b.current-a.current)[0],recent=sessions[0];return <section><div className="hero"><div><p className="eyebrow">WELCOME TO THE ROOM</p><h2>Rack &apos;em up, Steve.</h2><p>Live results from the pool room, available to everyone.</p><div className="button-row">{admin&&<button className="primary light" disabled={!data.players.length} onClick={add}>＋ Start a Play Day</button>}{recent&&<button className="secondary dark" onClick={()=>open(recent.id)}>View Latest →</button>}</div></div><div className="eight-ball">8</div></div><div className="metric-grid"><Metric icon="♛" label="CURRENT LEADER" value={leader?display(leader.player):"—"} detail={leader?`${leader.wins} wins · ${pct(leader.wins,leader.games)}`:"Record games to rank"}/><Metric icon="●" label="MOST ACTIVE" value={active?.games?display(active.player):"—"} detail={`${active?.games||0} games played`}/><Metric icon="↗" label="HOT STREAK" value={streak?.current?display(streak.player):"—"} detail={`${streak?.current||0} straight wins`}/><Metric icon="◷" label="LATEST PLAY DAY" value={recent?new Date(recent.date+"T12:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric"}):"—"} detail={recent?.name||"No sessions yet"}/></div><div className="two-col"><article className="panel"><div className="panel-title"><h3>Standings</h3></div><MiniStandings rows={standings.slice(0,5)}/></article><article className="panel"><div className="panel-title"><h3>Room totals</h3></div><div className="totals"><div><b>{data.sessions.length}</b><span>Play days</span></div><div><b>{games}</b><span>Games</span></div><div><b>{data.players.length}</b><span>Players</span></div></div>{recent?<button className="latest" onClick={()=>open(recent.id)}><span>Most recent</span><b>{recent.name||"Pool Night"}</b><small>{recent.games.length} games · View results →</small></button>:<p className="muted">Your first play day will appear here.</p>}</article></div></section>}
function Metric({icon,label,value,detail}:{icon:string;label:string;value:string;detail:string}){return <article className="metric"><span>{icon}</span><small>{label}</small><b>{value}</b><p>{detail}</p></article>}
function MiniStandings({rows}:{rows:ReturnType<typeof stats>}){return <div className="mini-table">{rows.length?rows.map((r,i)=><div key={r.player.id}><b className="rank">{i+1}</b><Avatar player={r.player} small/><span><b>{display(r.player)}</b><small>{r.wins}–{r.losses} record</small></span><strong>{pct(r.wins,r.games)}</strong></div>):<p className="muted">Add players and games to see standings.</p>}</div>}
function Standings({rows}:{rows:ReturnType<typeof stats>}){return <section><div className="section-heading"><div><h2>Lifetime records</h2><p>Automatically recalculated after every change.</p></div></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Player</th><th>Days</th><th>GP</th><th>W</th><th>L</th><th>Win %</th><th>Streak</th><th>Best</th><th>Last</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.player.id}><td>{i+1}</td><td><div className="player-cell"><Avatar player={r.player} small/><b>{display(r.player)}</b></div></td><td>{r.days}</td><td>{r.games}</td><td className="win">{r.wins}</td><td>{r.losses}</td><td><strong>{pct(r.wins,r.games)}</strong></td><td>{r.current}</td><td>{r.best}</td><td><span className={`result ${r.recent}`}>{r.recent}</span></td></tr>)}</tbody></table></div>{rows.map(r=>r.opponents.length?<article className="opponent-card" key={r.player.id}><h3>{display(r.player)} vs. the room</h3>{r.opponents.map(o=><span key={o.opponent.id}>{display(o.opponent)} <b>{o.wins}–{o.games-o.wins}</b></span>)}</article>:null)}</section>}
function HeadToHead({data,ids,setIds}:{data:Data;ids:[string,string];setIds:(x:[string,string])=>void}){const [a,b]=ids,pa=data.players.find(p=>p.id===a),pb=data.players.find(p=>p.id===b);const games=data.sessions.flatMap(s=>s.games.map(g=>({...g,date:s.date,session:s.name||"Pool Night"}))).filter(g=>a&&b&&[g.player1,g.player2].includes(a)&&[g.player1,g.player2].includes(b)).sort((x,y)=>y.date.localeCompare(x.date)||y.number-x.number);const aw=games.filter(g=>g.winner===a).length;return <section><div className="section-heading"><div><h2>Settle the rivalry</h2><p>Pick any two players for their complete matchup.</p></div></div><div className="h2h-pickers"><select value={a} onChange={e=>setIds([e.target.value,b])}><option value="">Player one</option>{data.players.map(p=><option value={p.id} key={p.id}>{display(p)}</option>)}</select><b>VS</b><select value={b} onChange={e=>setIds([a,e.target.value])}><option value="">Player two</option>{data.players.filter(p=>p.id!==a).map(p=><option value={p.id} key={p.id}>{display(p)}</option>)}</select></div>{pa&&pb?<><div className="versus"><div><Avatar player={pa}/><h3>{display(pa)}</h3><b>{aw}</b><span>{pct(aw,games.length)}</span></div><section><b>{games.length}</b><span>TOTAL GAMES</span></section><div><Avatar player={pb}/><h3>{display(pb)}</h3><b>{games.length-aw}</b><span>{pct(games.length-aw,games.length)}</span></div></div><div className="two-col"><article className="panel"><h3>By game type</h3>{TYPES.map(t=>{const x=games.filter(g=>g.type===t);return x.length?<p className="type-row" key={t}><span>{t}</span><b>{x.filter(g=>g.winner===a).length} – {x.filter(g=>g.winner===b).length}</b></p>:null})}</article><article className="panel"><h3>Recent games</h3>{games.slice(0,10).map(g=><p className="history-row" key={g.id}><span>{g.date}<small>{g.session} · {g.type}</small></span><b>{display(data.players.find(p=>p.id===g.winner))} won</b></p>)}{!games.length&&<p className="muted">No games against each other yet.</p>}</article></div></>:<Empty icon="↔" title="Choose two players" text="Their record, game types, and recent history will show here."/>}</section>}
function SessionView({admin,session,data,edit,add,editGame,removeGame,remove}:{admin:boolean;session:Session;data:Data;edit:()=>void;add:()=>void;editGame:(g:Game)=>void;removeGame:(g:Game)=>void;remove:()=>void}){const players=session.playerIds.map(id=>data.players.find(p=>p.id===id)).filter(Boolean) as Player[];const rows=players.map(p=>{const g=session.games.filter(x=>x.player1===p.id||x.player2===p.id),w=g.filter(x=>x.winner===p.id).length;return {p,g:g.length,w,l:g.length-w}}).sort((a,b)=>b.w-a.w||a.l-b.l);return <section><div className="session-hero"><div><p>{new Date(session.date+"T12:00:00").toLocaleDateString(undefined,{weekday:"long",year:"numeric",month:"long",day:"numeric"})}</p><div className="avatar-stack">{players.map(p=><Avatar key={p.id} player={p} small/>)}<span>{players.map(display).join(", ")}</span></div>{session.notes&&<blockquote>{session.notes}</blockquote>}</div>{admin&&<div className="button-row"><button className="secondary" onClick={edit}>✎ Edit day</button><button className="danger-button subtle" onClick={remove}>Archive</button></div>}</div><div className="summary-grid"><article className="panel"><small>TOTAL GAMES</small><b className="huge">{session.games.length}</b></article><article className="panel best"><small>BEST PLAYER</small>{rows[0]?.g?<><Avatar player={rows[0].p} small/><b>{display(rows[0].p)}</b><p>{rows[0].w} wins · {pct(rows[0].w,rows[0].g)}</p></>:<p className="muted">No results yet</p>}</article></div><article className="panel"><div className="panel-title"><h3>Session standings</h3></div><div className="mini-table">{rows.map((r,i)=><div key={r.p.id}><b className="rank">{i+1}</b><Avatar player={r.p} small/><span><b>{display(r.p)}</b><small>{r.w} wins · {r.l} losses</small></span><strong>{pct(r.w,r.g)}</strong></div>)}</div></article><div className="games-title"><div><h2>Games</h2><p>Chronological results from this play day.</p></div>{admin&&<button className="primary" disabled={players.length<2} onClick={add}>＋ {session.games.length?"Add Next Game":"Add First Game"}</button>}</div><div className="game-list">{[...session.games].sort((a,b)=>a.number-b.number).map(g=>{const winner=data.players.find(p=>p.id===g.winner),loser=data.players.find(p=>p.id===(g.winner===g.player1?g.player2:g.player1));return <article key={g.id}><b className="game-no">{g.number}</b><Avatar player={winner} small/><div className="grow"><h3>{display(winner)} <span>def.</span> {display(loser)}</h3><p>{g.type}{g.startTime&&` · ${g.startTime}`}{g.series&&` · ${g.series}`}</p>{g.notes&&<small>{g.notes}</small>}</div>{admin&&<><button className="icon-button" onClick={()=>editGame(g)}>✎</button><button className="icon-button danger" onClick={()=>removeGame(g)}>×</button></>}</article>})}</div>{admin&&session.games.length>0&&<button className="add-next" onClick={add}>＋ Add Next Game <span>Game {Math.max(...session.games.map(g=>g.number))+1}</span></button>}</section>}
function PlayerForm({player,index,close,save}:{player:Player|"new";index:number;close:()=>void;save:(e:FormEvent<HTMLFormElement>)=>void}){const p=player==="new"?undefined:player;return <Modal title={p?"Edit player":"Add a player"} close={close}><form onSubmit={save}><label>Name <input name="name" required autoFocus defaultValue={p?.name} placeholder="Full name"/></label><label>Nickname <input name="nickname" defaultValue={p?.nickname} placeholder="Optional table name"/></label><fieldset><legend>Profile color</legend><div className="colors">{COLORS.map((c,i)=><label key={c} style={{background:c}}><input type="radio" name="color" value={c} defaultChecked={p?p.color===c:i===index%COLORS.length}/><span>✓</span></label>)}</div></fieldset><div className="form-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Save Player</button></div></form></Modal>}
function SessionForm({session,players,close,save}:{session:Session|"new";players:Player[];close:()=>void;save:(e:FormEvent<HTMLFormElement>)=>void}){const s=session==="new"?undefined:session;return <Modal title={s?"Edit play day":"Start a play day"} close={close}><form onSubmit={save}><div className="form-grid"><label>Date <input name="date" type="date" required defaultValue={s?.date||today()}/></label><label>Session name <input name="name" defaultValue={s?.name} placeholder="Friday Night Pool"/></label></div><fieldset><legend>Who&apos;s playing?</legend><div className="player-checks">{players.map(p=><label key={p.id}><input type="checkbox" name="players" value={p.id} defaultChecked={s?s.playerIds.includes(p.id):true}/><Avatar player={p} small/><span>{display(p)}</span></label>)}</div></fieldset><label>Notes <textarea name="notes" defaultValue={s?.notes} placeholder="Optional notes about the night"/></label><div className="form-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">{s?"Save Changes":"Start Play Day"}</button></div></form></Modal>}
function GameForm({game,session,players,close,save}:{game:Game|"new";session:Session;players:Player[];close:()=>void;save:(e:FormEvent<HTMLFormElement>)=>void}){const g=game==="new"?undefined:game, available=session.playerIds.map(id=>players.find(p=>p.id===id)).filter(Boolean) as Player[], last=session.games.at(-1),p1=g?.player1||last?.player1||available[0]?.id,p2=g?.player2||last?.player2||available[1]?.id;return <Modal title={g?`Edit game ${g.number}`:`Add game ${Math.max(0,...session.games.map(x=>x.number))+1}`} close={close}><form onSubmit={save}>{g&&<label>Game number <input name="number" type="number" min="1" required defaultValue={g.number}/></label>}<div className="form-grid"><label>Player 1<select name="p1" defaultValue={p1}>{available.map(p=><option key={p.id} value={p.id}>{display(p)}</option>)}</select></label><label>Player 2<select name="p2" defaultValue={p2}>{available.map(p=><option key={p.id} value={p.id}>{display(p)}</option>)}</select></label></div><label>Winner<select name="winner" defaultValue={g?.winner||p1}>{available.map(p=><option key={p.id} value={p.id}>{display(p)}</option>)}</select></label><div className="form-grid"><label>Game type<select name="type" defaultValue={g?.type||(typeof window!=="undefined"&&localStorage.getItem("pool-last-type"))||"8-Ball"}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label>Start time<input name="time" type="time" defaultValue={g?.startTime}/></label></div><label>Race or series <input name="series" defaultValue={g?.series} placeholder="e.g. Race to 5"/></label><label>Game notes <textarea name="notes" defaultValue={g?.notes} placeholder="Optional"/></label><div className="form-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Save Game</button></div></form></Modal>}
function AuthModal({close,notify}:{close:()=>void;notify:(message:string)=>void}){const [sent,setSent]=useState(false);const login=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const email=String(new FormData(e.currentTarget).get("email")||"").trim();const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});if(error)notify(error.message);else setSent(true)};return <Modal title="Administrator sign in" close={close}>{sent?<div className="auth-success"><span>✉</span><h3>Check your email</h3><p>Use the secure Supabase magic link to return here. Only accounts listed in <code>admin_users</code> receive editing access.</p></div>:<form onSubmit={login}><p className="muted">Public results never require an account. Administrators can request a password-free magic link.</p><label>Email address<input type="email" name="email" required autoFocus autoComplete="email" placeholder="you@example.com"/></label><div className="form-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Email Magic Link</button></div></form>}</Modal>}
function MigrationPreview(){const [summary,setSummary]=useState("Checking this browser…");useEffect(()=>{try{if(localStorage.getItem("steves-pool-room-cloud-migrated")){setSummary("Already imported from this browser.");return}const raw=localStorage.getItem(STORAGE);if(!raw){setSummary("No local browser data found.");return}const old=JSON.parse(raw) as Data;setSummary(`${old.players?.length||0} players · ${old.sessions?.length||0} play days · ${old.sessions?.reduce((n,s)=>n+s.games.length,0)||0} games ready`) }catch{setSummary("Local data exists but could not be read.")}},[]);return <strong className="migration-preview">{summary}</strong>}
function Empty({icon,title,text}:{icon:string;title:string;text:string}){return <div className="empty"><span>{icon}</span><h3>{title}</h3><p>{text}</p></div>}
function download(name:string,content:string,type:string){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
